### ISSUE TITLE
Anonymous Token Question

### ISSUE THREAD

**Issue by ZQ-Dev8** [starmpcc/CAMEL#3]
Thank you for sharing this fantastic project. I'm hoping to replicate your process on different data from a totally separate domain.

One thing I'm struggling to understand is your addition of the [ANON] token during your tokenization process. I see this token gets inserted whenever a '___' string is found in the corpus. Could you explain why you did this? Is it something specific to the clinical notes you are processing?

**Comment by starmpcc** [comment]
Thank you for your interest!

We used the [ANON] token to prevent the model from learning the anonymization placeholder in the MIMIC-IV corpus.
In the MIMIC-III note dataset, personally identifiable information (PII) is replaced with corresponding categories, such as [\*\*NAME\*\*] or [\*\*2111-11-11\*\*]. 
However, in MIMIC-IV, every piece of PII is anonymized to a ___ placeholder, regardless of the type of PII. 
Since we did not want the model to learn this placeholder, we substituted these placeholders with the [ANON] token and masked them during the training stage.

**Comment by ZQ-Dev8** [comment]
@starmpcc Thank you very much for the quick reply! I've managed to set up and run a training pipeline that gives RedPajama-3B additional pretraining on domain-specific data. The pipeline is somewhat less sophisticated than your team's work (I don't have nearly as many tokens), but regardless I'm excited to check out the results. Thanks for the inspiration!
